### ISSUE TITLE
Full Installment Paid But Loan showing running

### ISSUE THREAD

**Issue by reduanmasud** [reduan-masud/ngoms#5]
![image](https://user-images.githubusercontent.com/59122533/112090256-6c7ad080-8bbd-11eb-8715-16ceb0965430.png)

**Comment by reduan-masud** [comment]
This problem may occur at member_profile.php page

**Comment by reduanmasud** [comment]
The Problem is in add_daily_money.php page
```cpp
isset($_GET['add_money'])) {
                $add_money = $loan->addMoney($_GET);
                echo $add_money['msg'];
                //var_dump($add_money);

```

**Comment by reduanmasud** [comment]
we have to check the **addMoney** method

**Comment by reduanmasud** [comment]
**addMoney** is a method of **Loan** Class
